//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SaludTeIntegra.WebApi.ServicioVisor {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="visor_clPortBinding", Namespace="http://metodos.visor_cl.saydex.custom.com/")]
    public partial class visor_clService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerURLVisorHCCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public visor_clService() {
            this.Url = global::SaludTeIntegra.WebApi.Properties.Settings.Default.SaludTeIntegra_WebApi_ServicioVisor_visor_clService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerURLVisorHCCCompletedEventHandler ObtenerURLVisorHCCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://metodos.visor_cl.saydex.custom.com/", ResponseNamespace="http://metodos.visor_cl.saydex.custom.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaObtenerURLVisorHCC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseTT ObtenerURLVisorHCC([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Request_TT parametro) {
            object[] results = this.Invoke("ObtenerURLVisorHCC", new object[] {
                        parametro});
            return ((responseTT)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerURLVisorHCCAsync(Request_TT parametro) {
            this.ObtenerURLVisorHCCAsync(parametro, null);
        }
        
        /// <remarks/>
        public void ObtenerURLVisorHCCAsync(Request_TT parametro, object userState) {
            if ((this.ObtenerURLVisorHCCOperationCompleted == null)) {
                this.ObtenerURLVisorHCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerURLVisorHCCOperationCompleted);
            }
            this.InvokeAsync("ObtenerURLVisorHCC", new object[] {
                        parametro}, this.ObtenerURLVisorHCCOperationCompleted, userState);
        }
        
        private void OnObtenerURLVisorHCCOperationCompleted(object arg) {
            if ((this.ObtenerURLVisorHCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerURLVisorHCCCompleted(this, new ObtenerURLVisorHCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metodos.visor_cl.saydex.custom.com/")]
    public partial class Request_TT {
        
        private int tipoIdentificacionPacienteField;
        
        private string numeroIdentificacionPacienteField;
        
        private string identificadorUnicoPacienteField;
        
        private string identificadorProfesionalField;
        
        private int sistemaSolicitaConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TipoIdentificacionPaciente {
            get {
                return this.tipoIdentificacionPacienteField;
            }
            set {
                this.tipoIdentificacionPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumeroIdentificacionPaciente {
            get {
                return this.numeroIdentificacionPacienteField;
            }
            set {
                this.numeroIdentificacionPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificadorUnicoPaciente {
            get {
                return this.identificadorUnicoPacienteField;
            }
            set {
                this.identificadorUnicoPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificadorProfesional {
            get {
                return this.identificadorProfesionalField;
            }
            set {
                this.identificadorProfesionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SistemaSolicitaConsulta {
            get {
                return this.sistemaSolicitaConsultaField;
            }
            set {
                this.sistemaSolicitaConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metodos.visor_cl.saydex.custom.com/")]
    public partial class responseTT {
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void ObtenerURLVisorHCCCompletedEventHandler(object sender, ObtenerURLVisorHCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerURLVisorHCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerURLVisorHCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseTT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseTT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591